import tarefas_verificador_dados_datasaver
import beneficios_verificador_dados_datasaver
import interacao_verificador_dados_datasaver
import atividadecontinuada_verificador_dados_datasaver
import auditoria_verificador_dados_datasaver
import monitoramento_verificador_dados_datasaver
import projetogeral_verificador_dados_datasaver
import achadosauditoria_verificador_dados_datasaver
import analiseauditoria_verificador_dados_datasaver
import analisepreliminar_verificador_dados_datasaver
import apuracaopreliminar_verificador_dados_datasaver
import autoavaliacaoiacm_verificador_dados_datasaver
import comunicacaoauditoria_verificador_dados_datasaver
import escopoauditoria_verificador_dados_datasaver
import execucaoconsultoria_verificador_dados_datasaver
import itemprocessoanalisetce_verificador_dados_datasaver
import itemtrabalhoatividade_verificador_dados_datasaver
import itemtrabalhoprojeto_verificador_dados_datasaver
import kpaiacm_verificador_dados_datasaver
import matrizplanejamento_verificador_dados_datasaver
import minutaposicionamento_verificador_dados_datasaver
import planejamentoconsultoria_verificador_dados_datasaver
import relatoriofinal_verificador_dados_datasaver
import relatoriopreliminar_verificador_dados_datasaver
import resultadosconsultoria_verificador_dados_datasaver
import termocompromissoconsultoria_verificador_dados_datasaver
import finalizador_programa
if __name__ == '__main__':
    # funções para executar os verificadores de dados com base nas tabelas tarefas_id e beneficios_id 
    tarefas_verificador_dados_datasaver.tarefas_verificador_dados()
    beneficios_verificador_dados_datasaver.beneficios_verificador_dados()
    interacao_verificador_dados_datasaver.interacao_verificador_dados()
    atividadecontinuada_verificador_dados_datasaver.atividade_continuada_verificador_dados()
    auditoria_verificador_dados_datasaver.auditoria_verificador_dados()
    monitoramento_verificador_dados_datasaver.monitoramento_verificador_dados()
    projetogeral_verificador_dados_datasaver.projeto_geral_verificador_dados()
    achadosauditoria_verificador_dados_datasaver.achados_auditoria_vericador_dados()
    analiseauditoria_verificador_dados_datasaver.analise_auditoria_verificador_dados()
    analisepreliminar_verificador_dados_datasaver.analise_preliminar_verificador_dados()
    apuracaopreliminar_verificador_dados_datasaver.apuracao_preliminar_verificador_dados()
    autoavaliacaoiacm_verificador_dados_datasaver.autoavaliacao_iacm_verificador_dados()
    comunicacaoauditoria_verificador_dados_datasaver.comunicacao_auditoria_verificador_dados()
    escopoauditoria_verificador_dados_datasaver.escopo_auditoria_verificdor_dados()
    execucaoconsultoria_verificador_dados_datasaver.execucao_consultoria_verificador_dados()
    itemprocessoanalisetce_verificador_dados_datasaver.itemprocesso_analise_tce_verificador_dados()
    itemtrabalhoatividade_verificador_dados_datasaver.item_trabalho_atividade_verificador_dados()
    itemtrabalhoprojeto_verificador_dados_datasaver.item_trabalho_projeto_verificador_dados()
    kpaiacm_verificador_dados_datasaver.kpa_iacm_verificador_dados()
    matrizplanejamento_verificador_dados_datasaver.matriz_planejamento_verificador_dados()
    minutaposicionamento_verificador_dados_datasaver.minuta_posicionamento_verificador_dados()
    planejamentoconsultoria_verificador_dados_datasaver.planejamento_consultoria_verificador_dados()
    relatoriofinal_verificador_dados_datasaver.relatorio_final_verificador_dados()
    relatoriopreliminar_verificador_dados_datasaver.relatorio_preliminar_verificador_dados()
    resultadosconsultoria_verificador_dados_datasaver.resultados_consultoria_verificador_dados()
    termocompromissoconsultoria_verificador_dados_datasaver.termo_compromisso_consultoria_verificador_dados()
    finalizador_programa.finalizador_programa()